services:
  - type: web
    name: nvps
    runtime: ruby
    buildCommand: bundle install
    startCommand: |
      bundle exec rake db:create db:migrate db:seed
      bundle exec rails s -b 0.0.0.0 -p $PORT